[package]
name = "leveldb-mcpe-sys"
version = "0.1.0"
authors = ["Luiz Ribeiro <luizribeiro@gmail.com>"]
edition = "2018"

links = "leveldb-mcpe"
build = "src/build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
